# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        order:
            persistence:
                driver: orm
                model: App\Entity\Order
                provider: ~
                finder: ~
                listener:
                    insert: false
                    update: true
                    delete: true
            properties:
                dish:
                    type: object
                    properties:
                        name: ~
                        price: ~
                        image: ~
                        category:
                            type: object
                            properties:
                                name: ~
                user:
                    type: object
                    properties:
                        name: ~
                        email: ~
                        address: ~
                status:
                    fielddata: true  # for aggregation
                isDelivery: ~
                createdAt: { type: date, format: epoch_millis||strict_date_optional_time }
                updatedAt: { type: date, format: epoch_millis||strict_date_optional_time }
