nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
        security:
            - Bearer: [ ]
        info:
            title: Cafe Manager API
            description: API routes for managing cafe's inventory, menu and orders.
            version: 1.0.0
    areas: # to filter documented areas
        orders:
            path_patterns:
                - ^/api/v\d/order
        default:
            path_patterns:
                - ^/api(?!/v\d/doc(.json)?$) # Accepts routes under /api except /api/v1/doc and /api/v1/doc.json
