old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        create_order:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.create_order', type: direct}

    consumers:
        create_order:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.create_order', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.create_order'}
            callback: App\Consumer\CreateOrder\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 1, global: false}
